name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.218.50.206 "echo 'CI/CD SUCCESS MAMA' | sudo tee /var/www/html/index.html"
